[33m0e14fc8[m[33m ([m[1;36mHEAD -> [m[1;32mmain[m[33m, [m[1;31morigin/main[m[33m)[m 016: Admin site implementation.
[33m64aff1e[m 015: Form layout added.
[33m62b47e7[m 014: Login Conectado.
[33ma329701[m 013: Detailed card component added. Responsive design. Add more images still pending.
[33mb80e7d2[m 012: Login page added. Figma design implemented. Connection with backend still pending.
[33m8fea3c0[m 011: Light and Dark theme added. Context working. Ready for session managment.
[33m921a6ca[m 010: File restructuration for images implemented (this is temporal, replace it with database connection for storing images). Placeholder images added.
[33m5108863[m 09: Tetimonies Templete grid and card created, Transparency template added. Other minor changes implemented, fonts margins, sizes etc.
[33me02d2d7[m 08: Footer component created and implementd.
[33m702cb52[m 07: Cardcarrousel component created and added to the projects and programs pages using dummy data file (update it later).
[33m7088457[m 06: Corrections requested by the client implemented. Fonts added (Numbers arent working due to the trial version), Patreons carrousel modified, navbar links modified, and some color corrections.
[33m1f7242c[m 06: Event page template, added, standarization of cards in progress. Modular css implemented, restructuration of file tree.
[33m4db8fed[m 05: Icons added, home
[33mb52a0c1[m 04: Navbar fixed, svg added
[33m7397dae[m 03: Navigation implemented
[33mbe376c1[m 02: Home page implementation
[33md281051[m 01: Setup GitHub Pages deployment
[33mf921339[m zero: Project initialization
